In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np
numbers = [1,2,3,4]



In [6]:
numbers *2

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
arr = np.array([1,2,3,4,5,6,7])


In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
arr *2


array([ 2,  4,  6,  8, 10, 12, 14])

In [10]:
arr1 = np.array([0])

In [11]:
arr1

array([0])

In [13]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [17]:
arr4 = np.ones(5)
arr4

array([1., 1., 1., 1., 1.])

In [18]:
arr5 = np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(0,10,1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [26]:
arr2.shape

(2, 4)

In [25]:
arr2.size

8

In [27]:
arr2.dtype

dtype('int64')

In [28]:
arr2.ndim

2

In [30]:
arr6=np.array([1,2,3],dtype=np.float32)
arr6

array([1., 2., 3.], dtype=float32)

In [31]:
arr7 = np.array([1,2,3,4,5,6,7])
arr7


array([1, 2, 3, 4, 5, 6, 7])

In [32]:
arr7[2]

np.int64(3)

In [33]:
arr7[-1]

np.int64(7)

In [34]:
arr[-2]

np.int64(6)

In [35]:
arr[1:3]

array([2, 3])

In [38]:
arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr8


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr8[1,1]

np.int64(5)

In [44]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [45]:
a-b

array([-4, -4, -4, -4])

In [46]:
a+b

array([ 6,  8, 10, 12])

In [47]:
a*b

array([ 5, 12, 21, 32])

In [48]:
a**b

array([    1,    64,  2187, 65536])

In [49]:
c = np.array([10,20,30,40])

In [50]:
c.mean()

np.float64(25.0)

In [53]:

c.max()

np.int64(40)

In [54]:
c.sum()

np.int64(100)

In [55]:
c.min()

np.int64(10)

In [56]:
d = np.array([1,2,3,4,5,6,7,8,9,10])

In [57]:
d.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
e = np.array([1,2,3,4,5,6,7,8,9])
e.reshape((-1,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
f = np.random.rand(3,4)
f

array([[0.01705882, 0.62038969, 0.77048049, 0.91116931],
       [0.61144013, 0.325968  , 0.7366021 , 0.94218392],
       [0.28330043, 0.68177941, 0.68439072, 0.60247114]])